services:
  haproxy:
    build: ./haproxy
    container_name: haproxy-lb
    ports:
      - "8082:80"
    networks:
      web-network:
        ipv4_address: 172.20.0.10
    depends_on:
      - web-01
      - web-02
    restart: unless-stopped

  web-01:
    build: .
    container_name: web-server-01
    networks:
      web-network:
        ipv4_address: 172.20.0.11
    restart: unless-stopped
    environment:
      - SERVER_NAME=web-01
    env_file: 
      - .env
    ports:
      - "8080:3005"

  web-02:
    build: .
    container_name: web-server-02
    networks:
      web-network:
        ipv4_address: 172.20.0.12
    restart: unless-stopped
    environment:
      - SERVER_NAME=web-02
    env_file: 
      - .env
    ports:
      - "8081:3005"
networks:
  web-network:
    driver: bridge 
    ipam:
      config:
        - subnet: 172.20.0.0/24